### ISSUE TITLE
Make new release from #13

### ISSUE THREAD

**Issue by regiszanandrea** [radmen/adonis-lucid-soft-deletes#15]
Hi, 

I'm using this package and I would like to use this feature from #13 .

Can you make a new release from that? 

Thanks

**Comment by rsantos** [comment]
Up

**Comment by radmen** [comment]
@regiszanandrea @rsantos which version are you using? This feature should be included in `v0.2.0`. It's already published on NPM.

**Comment by regiszanandrea** [comment]
@radmen You're right, my bad.
