### ISSUE TITLE
Format exclusion date same as creation date

### ISSUE THREAD

**Issue by waldenermonteiro** [radmen/adonis-lucid-soft-deletes#8]
Hello, how are you?
What is the possibility of leaving the date exactly like create_at and update at?
Example:
2019-09-13 16:49:50
In the case of your library, it saves as:
2019-09-12T21: 31: 04.000Z
I checked the code and tried to implement this formatting but couldn't

Hugs

**Comment by radmen** [comment]
@waldenermonteiro I might be wrong but are you referring to the [date fields](https://adonisjs.com/docs/4.0/lucid#_defining_date_fields)?

If not - could you provide an example use case?

Thanks!

**Comment by waldenermonteiro** [comment]
Yes, I am.

Adonis saves format creation and change dates : 2019-09-13 16:49:50.
And your library saves as: 2019-09-12T21: 31: 04.000Z.

So I would like to know if you had your library save exactly the same format as adonis saves.
If not, could you point me to an alternative?

Thanks for answering

**Comment by radmen** [comment]
@waldenermonteiro have you tried adding `dates` static getter?

```js
static get dates () {
  return super.dates.concat(['deleted_at'])
}
```

Let me know if this solves your problem. If yes - I'll update package with this fix.

**Comment by waldenermonteiro** [comment]
Thank you very much. I'm still starting with adonis, it's a very simple solution, and besides solving my problem, it gave me the idea of ​​formatting already in Brazilian format for the front end.

**Comment by radmen** [comment]
@waldenermonteiro I'm glad that it helped. I'm going to keep this issue as a reminder that I should fix this in the package :)
